### ISSUE TITLE
What is inputNode?

### ISSUE THREAD

**Issue by jnsandrew** [WiaczeslawP/react-screen-keyboard#4]
Can I have an example of how to pass an inputNode into the component? I've tried various combinations but I always get the error:

`Keyboard.js:114 Uncaught TypeError: Cannot read property 'type' of undefined`

**Comment by GiovanniFrigo** [comment]
Same problem here. It's a pity we can't use this component just because it's missing some proper documentation and some examples!

Out of frustration I ended up downloading the code and modifying it to my needs.

**Comment by WiaczeslawP** [comment]
I updated the readme file, so now I hope the description is more clear

**Comment by dcwangmit01** [comment]
@WiaczeslawP. I'm still having the same problem as @jnsandrew and @GiovanniFrigo, even with the updated documentation.  It would be great if you could provide a complete example.  I'm no Javascript expert, but I do believe I've tried enough permutations that it should have worked.

Problem stems from inputNode.dataset which is null.
```
lib/Keyboard.js:138:                    return inputNode.type !== 'password' && inputNode.dataset.type !== 'email' && !inputNode.value.length && isFirstLetterUppercase;
``` 

I'll keep trying, but if anyone has succeeded, a response would be helpful.

**Comment by karthi30** [comment]
@WiaczeslawP.  I'm also facing the same problem. @dcwangmit01 if you solved, please share the solution.

**Comment by dcwangmit01** [comment]
@karthi30 I ended up using this: https://github.com/xtrinch/react-touch-screen-keyboard , which is built on this code base, and packaged up nicely.  The project itself is a nice example of how to use this one.

**Comment by karthi30** [comment]
@dcwangmit01 thanks for the info.

**Comment by chfritz** [comment]
Yes, this seems a little tricky, because the component wants a ref but in most cases the ref will not have a "current" yet. I was able to solve this using the state:

```js
  <input
    type="text"
    ref={(input) => this.input = input}
    placeholder="Type to add new tasks"
    onFocus={(input) => this.setState({inputNode: this.input})}
  />
  {this.state.inputNode ?
    <Keyboard
      inputNode={this.state.inputNode}
      layouts={[LatinLayout]}/> : ''}
```
